# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c53c3f52afb5613448a31853f4480b5dbb8c6ccdac67c603844928cf4b9cd434e8bb5e9dae043fb57dc67954538eecb06dd9ae881804131e05d434800a4963e0

test:
  secret_key_base: a8c3e5a2425da9ffaed5898b58d49dede906f6f83c7e38640387a1eb391c74c4fcf9b287d3363c014d9f950bc7e46d9918a8231c434612154ff0a47f186ed656

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
